package com.nssol.dao.master;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nssol.model.TBasicInfo;

@Mapper
public interface TBasicInfoDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.users
	 *
	 * @mbg.generated Mon Jan 15 14:03:52 CST 2018
	 */
	List<TBasicInfo> selectByskuCode(TBasicInfo basicInfo);

	public TBasicInfo getBasicInfo(TBasicInfo tBasicInfo);

	public void setBasicInfo(TBasicInfo tBasicInfo);

}