package com.nssol.dao.master;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nssol.model.TMetalcheck;

@Mapper
public interface TMetalcheckDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.users
	 *
	 * @mbg.generated Mon Jan 15 14:03:52 CST 2018
	 */
	List<TMetalcheck> selectByCriteria(TMetalcheck tInspection);
	
	void insertMetalcheck(TMetalcheck tInspection);

	List<TMetalcheck> selectMetalchecklist(TMetalcheck tInspectiong);
	
	List<TMetalcheck> selectTotMetalchecklist(TMetalcheck tInspection);
	
	List<TMetalcheck> selectMetalchecklistCount(TMetalcheck tInspection);
	
	TMetalcheck selectIdBysku(TMetalcheck tInspection);
	
	void updateMetalcheck(TMetalcheck tInspection);

	void deleteMetalcheckData();
}