package com.nssol.dao.master;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nssol.model.TMstDictionary;

@Mapper
public interface TMstDictionaryDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.users
	 *
	 * @mbg.generated Mon Jan 15 14:03:52 CST 2018
	 */
	List<TMstDictionary> getMstDictionary(TMstDictionary mstDict);

	List<TMstDictionary> getEnableAddress(TMstDictionary mstDict);

	void setMstDictionary(TMstDictionary mstDict);

	void clearAddress (TMstDictionary mstDict);
}