package com.nssol.dao.master;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nssol.model.TOrderDetail;;

@Mapper
public interface TOrderDetailDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.users
	 *
	 * @mbg.generated Mon Jan 15 14:03:52 CST 2018
	 */
	TOrderDetail selectByskuCode(TOrderDetail orderDetail);

	List<TOrderDetail> selectOrderDetailBysku(TOrderDetail orderDetail);
	
	List<TOrderDetail> selectSkuListByOrderNo(TOrderDetail orderDetail);

}