package com.nssol.dao.master;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nssol.model.T_Tagging;

@Mapper
public interface TTaggingDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.users
	 *
	 * @mbg.generated Mon Jan 15 14:03:52 CST 2018
	 */
	List<T_Tagging> selectByCriteria(T_Tagging tTagging);
	
	void insertTagging(T_Tagging tTagging);

	List<T_Tagging> selectTagginglist(T_Tagging tTagging);
	
	List<T_Tagging> selectTotTagginglist(T_Tagging tTagging);
	
	List<T_Tagging> selectTagginglistCount(T_Tagging tTagging);
	
	T_Tagging selectIdBysku(T_Tagging tTagging);
	
	void updateTagging(T_Tagging tTagging);
}